export interface Tool {
  name: string;
  slug: string;
  description: string;
  category: string;
  color: string;
  icon: string;
  available: boolean;
  seoTitle: string;
  seoDescription: string;
  longTailKeywords: string[];
}

export const categories = [
  { id: "all", label: "All Tools" },
  { id: "organize", label: "Organize PDF" },
  { id: "convert", label: "Convert PDF" },
  { id: "edit", label: "Edit PDF" },
  { id: "optimize", label: "Optimize PDF" },
  { id: "security", label: "PDF Security" },
  { id: "intelligence", label: "PDF Intelligence" },
] as const;

export const tools: Tool[] = [
  // Organize PDF
  { name: "Merge PDF", slug: "merge-pdf", description: "Combine multiple PDFs into one file in the order you want.", category: "organize", color: "#E74C3C", icon: "merge", available: true,
    seoTitle: "Merge PDF Files Online — Free & Fast | Combine PDFs Instantly",
    seoDescription: "Merge multiple PDF files into one document for free. Drag and drop to reorder, combine unlimited PDFs online. No registration, no watermarks.",
    longTailKeywords: ["merge pdf online free", "combine pdf files", "join pdf documents", "merge multiple pdfs into one", "pdf combiner online free"] },
  { name: "Split PDF", slug: "split-pdf", description: "Separate a PDF into individual single-page files.", category: "organize", color: "#E74C3C", icon: "split", available: true,
    seoTitle: "Split PDF Online — Separate PDF Pages for Free",
    seoDescription: "Split a PDF into individual pages or extract specific page ranges. Free online PDF splitter — no installation, instant download.",
    longTailKeywords: ["split pdf online free", "separate pdf pages", "extract pages from pdf", "pdf page splitter", "divide pdf into pages"] },
  { name: "Remove Pages", slug: "remove-pages", description: "Delete specific pages from your PDF document.", category: "organize", color: "#E74C3C", icon: "remove", available: true,
    seoTitle: "Remove Pages from PDF Online — Delete PDF Pages Free",
    seoDescription: "Delete unwanted pages from your PDF document instantly. Select and remove specific pages — free, online, no sign-up required.",
    longTailKeywords: ["remove pages from pdf", "delete pdf pages online", "remove page from pdf free", "pdf page remover"] },
  { name: "Extract Pages", slug: "extract-pages", description: "Pull selected pages into a new PDF file.", category: "organize", color: "#E74C3C", icon: "extract", available: true,
    seoTitle: "Extract Pages from PDF Online — Pull Pages into New PDF",
    seoDescription: "Extract specific pages from a PDF and save them as a new document. Free online PDF page extractor — fast and easy.",
    longTailKeywords: ["extract pages from pdf", "pull pages from pdf", "save specific pdf pages", "pdf page extractor online"] },
  { name: "Rotate PDF", slug: "rotate-pdf", description: "Rotate your PDF pages the way you need them.", category: "organize", color: "#E74C3C", icon: "rotate", available: true,
    seoTitle: "Rotate PDF Online — Turn PDF Pages 90°, 180°, 270° Free",
    seoDescription: "Rotate PDF pages by 90, 180, or 270 degrees. Fix upside-down or sideways scans instantly. Free online PDF rotator.",
    longTailKeywords: ["rotate pdf online", "rotate pdf pages", "turn pdf sideways", "flip pdf orientation", "pdf rotator free"] },
  { name: "Compress PDF", slug: "compress-pdf", description: "Reduce file size while optimizing for quality.", category: "organize", color: "#E67E22", icon: "compress", available: true,
    seoTitle: "Compress PDF Online — Reduce PDF Size Without Losing Quality",
    seoDescription: "Compress PDF files to reduce size while keeping quality. Free online PDF compressor — shrink PDFs for email, upload, or sharing.",
    longTailKeywords: ["compress pdf online free", "reduce pdf file size", "compress pdf without losing quality", "pdf compressor online", "shrink pdf size"] },
  { name: "Organize PDF", slug: "organize-pdf", description: "Sort pages in any order. Delete or add pages.", category: "organize", color: "#E74C3C", icon: "organize", available: true,
    seoTitle: "Organize PDF Pages Online — Reorder, Remove & Sort Pages",
    seoDescription: "Rearrange PDF pages in any order. Drag to reorder, remove unwanted pages. Free online PDF organizer tool.",
    longTailKeywords: ["organize pdf pages", "reorder pdf pages online", "rearrange pdf", "sort pdf pages", "pdf page organizer"] },
  { name: "Page Numbers", slug: "page-numbers", description: "Add page numbers to your PDF with custom position.", category: "organize", color: "#E74C3C", icon: "numbers", available: true,
    seoTitle: "Add Page Numbers to PDF Online — Free PDF Numbering Tool",
    seoDescription: "Add page numbers to any PDF document. Choose position (top/bottom, left/center/right) and starting number. Free online tool.",
    longTailKeywords: ["add page numbers to pdf", "pdf page numbering", "insert page numbers pdf", "number pdf pages online free"] },

  // Convert to PDF
  { name: "JPG to PDF", slug: "jpg-to-pdf", description: "Convert JPG images to PDF in seconds.", category: "convert", color: "#3498DB", icon: "image", available: true,
    seoTitle: "JPG to PDF — Convert Images to PDF Online Free",
    seoDescription: "Convert JPG, JPEG, and PNG images to PDF documents instantly. Free online image to PDF converter — no watermarks, no limits.",
    longTailKeywords: ["jpg to pdf", "convert jpg to pdf", "image to pdf converter", "jpeg to pdf online free", "photo to pdf"] },
  { name: "Word to PDF", slug: "word-to-pdf", description: "Convert DOC and DOCX files to PDF.", category: "convert", color: "#3498DB", icon: "word", available: true,
    seoTitle: "Word to PDF — Convert DOCX to PDF Online Free",
    seoDescription: "Convert Word documents (DOC, DOCX) to PDF format instantly. Free online Word to PDF converter with formatting preserved.",
    longTailKeywords: ["word to pdf", "convert docx to pdf", "doc to pdf online free", "word document to pdf converter"] },
  { name: "PowerPoint to PDF", slug: "ppt-to-pdf", description: "Convert PPT and PPTX slides to PDF.", category: "convert", color: "#3498DB", icon: "ppt", available: true,
    seoTitle: "PowerPoint to PDF — Convert PPTX to PDF Online Free",
    seoDescription: "Convert PowerPoint presentations (PPT, PPTX) to PDF. Free online converter — preserve slides layout and content.",
    longTailKeywords: ["ppt to pdf", "convert powerpoint to pdf", "pptx to pdf online free", "presentation to pdf"] },
  { name: "Excel to PDF", slug: "excel-to-pdf", description: "Convert XLSX spreadsheets to PDF.", category: "convert", color: "#3498DB", icon: "excel", available: true,
    seoTitle: "Excel to PDF — Convert Spreadsheets to PDF Online Free",
    seoDescription: "Convert Excel spreadsheets (XLSX, XLS, CSV) to PDF documents. Free online converter with table formatting preserved.",
    longTailKeywords: ["excel to pdf", "convert xlsx to pdf", "spreadsheet to pdf online free", "xls to pdf converter"] },
  { name: "HTML to PDF", slug: "html-to-pdf", description: "Convert HTML content to PDF documents.", category: "convert", color: "#3498DB", icon: "html", available: true,
    seoTitle: "HTML to PDF — Convert Web Content to PDF Online Free",
    seoDescription: "Convert HTML code or web content to PDF documents. Free online HTML to PDF converter — paste code, get PDF instantly.",
    longTailKeywords: ["html to pdf", "convert html to pdf", "webpage to pdf", "web page to pdf converter online"] },

  // Convert from PDF
  { name: "PDF to JPG", slug: "pdf-to-jpg", description: "Convert each PDF page into a JPG image.", category: "convert", color: "#3498DB", icon: "image", available: true,
    seoTitle: "PDF to JPG — Convert PDF Pages to Images Online Free",
    seoDescription: "Convert PDF pages to high-quality JPG images. Preview and download individual pages. Free online PDF to image converter.",
    longTailKeywords: ["pdf to jpg", "convert pdf to jpg", "pdf to image converter", "pdf to jpeg online free", "save pdf as jpg"] },
  { name: "PDF to Word", slug: "pdf-to-word", description: "Convert PDF to editable Word documents.", category: "convert", color: "#3498DB", icon: "word", available: true,
    seoTitle: "PDF to Word — Convert PDF to Editable DOCX Online Free",
    seoDescription: "Convert PDF files to editable Word documents. Extract text and formatting from any PDF. Free online PDF to Word converter.",
    longTailKeywords: ["pdf to word", "convert pdf to docx", "pdf to word converter online free", "pdf to editable document"] },
  { name: "PDF to PowerPoint", slug: "pdf-to-ppt", description: "Turn your PDF into a PPTX slideshow.", category: "convert", color: "#3498DB", icon: "ppt", available: true,
    seoTitle: "PDF to PowerPoint — Convert PDF to Slides Online Free",
    seoDescription: "Convert PDF pages to PowerPoint slide images. Export as high-quality images ready for presentations. Free online converter.",
    longTailKeywords: ["pdf to ppt", "convert pdf to powerpoint", "pdf to pptx online free", "pdf to presentation converter"] },
  { name: "PDF to Excel", slug: "pdf-to-excel", description: "Extract PDF tables into XLSX spreadsheets.", category: "convert", color: "#3498DB", icon: "excel", available: true,
    seoTitle: "PDF to Excel — Extract Tables to Spreadsheet Online Free",
    seoDescription: "Extract tables and data from PDF files into Excel spreadsheets (XLSX). Free online PDF to Excel converter.",
    longTailKeywords: ["pdf to excel", "convert pdf to xlsx", "extract tables from pdf", "pdf to spreadsheet online free"] },
  { name: "PDF to PDF/A", slug: "pdf-to-pdfa", description: "Convert to ISO-standard archive format.", category: "convert", color: "#3498DB", icon: "archive", available: true,
    seoTitle: "PDF to PDF/A — Convert to Archival Format Online Free",
    seoDescription: "Convert PDF to ISO-standard PDF/A archival format for long-term preservation. Embed metadata and standardize structure.",
    longTailKeywords: ["pdf to pdfa", "convert pdf to pdf/a", "pdf archival format", "iso 19005 converter", "pdf long term preservation"] },
  { name: "PDF to Markdown", slug: "pdf-to-markdown", description: "Convert PDF to Markdown for notes and docs.", category: "convert", color: "#3498DB", icon: "markdown", available: true,
    seoTitle: "PDF to Markdown — Convert PDF to MD Format Online Free",
    seoDescription: "Convert PDF documents to Markdown format. Extract text with page structure for notes and documentation. Free online converter.",
    longTailKeywords: ["pdf to markdown", "convert pdf to md", "pdf to text converter", "extract text from pdf as markdown"] },

  // Edit PDF
  { name: "Edit PDF", slug: "edit-pdf", description: "Add text, images, shapes, and annotations.", category: "edit", color: "#27AE60", icon: "edit", available: true,
    seoTitle: "Edit PDF Online — Add Text, Annotations & Images Free",
    seoDescription: "Edit PDF files online for free. Add text annotations, choose fonts, colors, and positions. No software installation needed.",
    longTailKeywords: ["edit pdf online free", "add text to pdf", "pdf editor online", "annotate pdf online", "modify pdf free"] },
  { name: "Sign PDF", slug: "sign-pdf", description: "Draw and place your signature on PDF pages.", category: "edit", color: "#27AE60", icon: "sign", available: true,
    seoTitle: "Sign PDF Online — Draw & Place Signature on PDF Free",
    seoDescription: "Draw your signature and place it on any PDF page. Touch-screen support for mobile signing. Free online PDF signature tool.",
    longTailKeywords: ["sign pdf online free", "add signature to pdf", "electronic signature pdf", "draw signature on pdf", "e-sign pdf free"] },
  { name: "Watermark", slug: "watermark", description: "Stamp text or image watermarks on pages.", category: "edit", color: "#27AE60", icon: "watermark", available: true,
    seoTitle: "Add Watermark to PDF Online — Text Watermark Free",
    seoDescription: "Add custom text watermarks to your PDF pages. Adjust opacity, font size, and rotation. Free online PDF watermark tool.",
    longTailKeywords: ["add watermark to pdf", "pdf watermark online free", "stamp pdf with text", "watermark pdf pages"] },
  { name: "PDF Forms", slug: "pdf-forms", description: "Fill interactive form fields in your PDF.", category: "edit", color: "#27AE60", icon: "forms", available: true,
    seoTitle: "Fill PDF Forms Online — PDF Form Filler Free",
    seoDescription: "Fill interactive PDF form fields online. Detect text fields, fill values, and flatten forms. Free online PDF form filler.",
    longTailKeywords: ["fill pdf form online", "pdf form filler free", "edit pdf form fields", "fillable pdf online"] },
  { name: "Redact PDF", slug: "redact-pdf", description: "Permanently remove sensitive content.", category: "edit", color: "#27AE60", icon: "redact", available: true,
    seoTitle: "Redact PDF Online — Black Out Sensitive Content Free",
    seoDescription: "Permanently redact sensitive content in PDF documents. Cover text with black rectangles that cannot be removed. Free online tool.",
    longTailKeywords: ["redact pdf online", "black out text in pdf", "censor pdf content", "remove sensitive info from pdf free"] },
  { name: "Crop PDF", slug: "crop-pdf", description: "Adjust margins and crop page areas.", category: "edit", color: "#27AE60", icon: "crop", available: true,
    seoTitle: "Crop PDF Online — Trim Margins & Resize Pages Free",
    seoDescription: "Crop PDF pages by adjusting margins. Trim whitespace and resize page areas. Free online PDF cropping tool.",
    longTailKeywords: ["crop pdf online", "trim pdf margins", "resize pdf pages", "cut pdf borders", "pdf cropper free"] },

  // Optimize PDF
  { name: "Repair PDF", slug: "repair-pdf", description: "Fix damaged or corrupted PDF files.", category: "optimize", color: "#E67E22", icon: "repair", available: true,
    seoTitle: "Repair PDF Online — Fix Corrupted PDF Files Free",
    seoDescription: "Fix damaged or corrupted PDF files. Recover pages and reconstruct document structure. Free online PDF repair tool.",
    longTailKeywords: ["repair pdf online", "fix corrupted pdf", "recover damaged pdf", "pdf repair tool free", "broken pdf fix"] },
  { name: "Compare PDF", slug: "compare-pdf", description: "Side-by-side comparison of two PDFs.", category: "optimize", color: "#E67E22", icon: "compare", available: true,
    seoTitle: "Compare PDF Files Online — Side-by-Side Diff Free",
    seoDescription: "Compare two PDF documents side by side. Visual page-by-page comparison to spot differences. Free online PDF comparison tool.",
    longTailKeywords: ["compare pdf files", "pdf comparison online", "diff two pdfs", "side by side pdf compare free"] },
  { name: "Scan to PDF", slug: "scan-to-pdf", description: "Capture document scans from your camera.", category: "optimize", color: "#E67E22", icon: "scan", available: true,
    seoTitle: "Scan to PDF — Camera Document Scanner Online Free",
    seoDescription: "Scan documents with your phone or webcam and convert to PDF. Multi-page capture support. Free online document scanner.",
    longTailKeywords: ["scan to pdf online", "camera to pdf", "document scanner online", "phone scan to pdf", "mobile document scanner"] },

  // Security
  { name: "Unlock PDF", slug: "unlock-pdf", description: "Remove PDF password protection.", category: "security", color: "#8E44AD", icon: "unlock", available: true,
    seoTitle: "Unlock PDF Online — Remove Password Protection Free",
    seoDescription: "Remove password protection from PDF files. Unlock restricted PDFs for editing, printing, and copying. Free online tool.",
    longTailKeywords: ["unlock pdf online", "remove pdf password", "pdf password remover free", "unprotect pdf", "decrypt pdf online"] },
  { name: "Protect PDF", slug: "protect-pdf", description: "Add protection watermark to your PDF.", category: "security", color: "#8E44AD", icon: "lock", available: true,
    seoTitle: "Protect PDF Online — Add Security Watermark Free",
    seoDescription: "Protect your PDF with security watermarks (CONFIDENTIAL, DO NOT COPY). Prevent unauthorized distribution. Free online tool.",
    longTailKeywords: ["protect pdf online", "add security to pdf", "pdf protection free", "watermark confidential pdf"] },

  // Intelligence
  { name: "OCR PDF", slug: "ocr-pdf", description: "Extract text from scanned documents.", category: "intelligence", color: "#16A085", icon: "ocr", available: true,
    seoTitle: "OCR PDF Online — Extract Text from PDF Free",
    seoDescription: "Extract text from PDF documents using OCR. Get word count, download as text file or copy to clipboard. Free online OCR tool.",
    longTailKeywords: ["ocr pdf online free", "extract text from pdf", "pdf to text converter", "scan pdf to text", "pdf text extraction"] },
  { name: "AI Summarizer", slug: "ai-summarizer", description: "Generate concise AI-powered summaries.", category: "intelligence", color: "#16A085", icon: "ai", available: true,
    seoTitle: "AI PDF Summarizer — Smart Document Summary Free",
    seoDescription: "Generate AI-powered summaries of your PDF documents. Extract key points and top keywords. Brief or detailed modes. Free online tool.",
    longTailKeywords: ["ai pdf summarizer", "summarize pdf online free", "pdf summary generator", "extract key points from pdf"] },
  { name: "Translate PDF", slug: "translate-pdf", description: "Extract text and translate PDF documents.", category: "intelligence", color: "#16A085", icon: "translate", available: true,
    seoTitle: "Translate PDF Online — PDF Translation to 12+ Languages Free",
    seoDescription: "Extract text from PDFs and translate to 12+ languages via Google Translate. Download extracted text. Free online PDF translator.",
    longTailKeywords: ["translate pdf online free", "pdf translator", "convert pdf to another language", "pdf translation tool"] },
];
